config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  
  resources :records

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
  end
  
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def index
    @records = Record.all
  end

  def create
    @record = Record.new(record_params)

    if @record.save
      render json: @record
    else
      render json: @record.errors, status: :unprocessible_entity
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    head :no_content
  end 

    private

    def record_params
      params.require(:record).permit(:title, :amount, :date)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/index/index.html.erb
<div id="home">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1 id="home-h1">Bankr</h1>
          <h3 id="home-h3">The hippest way to manage your money.<br><br>
            <%= link_to "Get Started", records_path, class: "btn-custom" %>
          </h3>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">

<div class="container">

  <div class="text-center center-block">
     <i id="social-em" class="fa fa-envelope-open-o fa-3x social" aria-hidden="true"></i>
     <i id="social-fb" class="fa fa-facebook fa-3x social" aria-hidden="true"></i>
     <i id="social-ig" class="fa fa-instagram fa-3x social" aria-hidden="true"></i>
     <i id="social-tw" class="fa fa-twitter fa-3x social" aria-hidden="true"></i>
     <i id="social-md" class="fa fa-medium fa-3x social" aria-hidden="true"></i>
  </div>
</div>
<br><br>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accounts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Roboto+Mono" rel="stylesheet">
  </head>

  <body>



      <%= yield %>


<%= render :partial => "layouts/footer"  if controller_name == "records" %>


  </body>
</html>

app/views/records/index.html.erb
<div id="records">
  <div class="container">
    <%= react_component 'Records', { data: @records } %>
  </div>
</div>